export const questions = [
  [
    "Hello! Thank you for participating in our study on healthcare communication!",
    "Those who have a physical chronic illness have stories that they share when it comes to their illness. Sometimes there is one particular memory that stands out for you related to your illness. This memory often has some of the following attributes:",
    `\u2022 It is a memory regarding your illness that has occurred before or after diagnosis.\n\u2022 It is a memory related to your illness for a specific moment or event that is very clear in your mind. It stands out in your mind. It probably still feels important to you even as you think about it, and it may lead to strong feelings\n\u2022 It is a memory you might tell someone else if that person asked about what it is like to have your physical chronic illness.\n\u2022 It is a memory that you think about when you think of your chronic illness. It feels vivid/clear, and may even feel familiar.`,
    "Please write about the memory you have that you always think about in regards to your illness. Please be as specific as possible, and be sure to include what happened, who was there, where it was, and when it happened. Do not share identifying information (like your name, address, etc.). Feel free to write as much as you want (the more the better) about your memory.",
    "PATIENT RESPONDS",
    "I also have a chronic condition. A few years back, I was diagnosed with Multiple sclerosis. I was really surprised because I have always lived a healthy lifestyle, and before that I had been going along normally. It’s a painful disease and so far there is really no way to cure it. It eventually will cause blurred vision, muscle weakness, and fatigue but right now it’s mostly numbness in my body. Sometimes it’s just my legs and arms that get tingling, but on other days, the numbness gets quite bad. My MS attacks tend to happen a few times a year. They mainly only happen about one to two times a year, so for the most part I’m still able to live my day to day life. But my episodes can be very grueling when they do happen.",
    "There was one time, about a year ago, where it became unbearable. It was mostly in my legs more than anything else, and I was experiencing extreme fatigue. The worst part about the numbness is that it really interferes with my day-to-day life because of course your limbs are so central to moving around: getting up, sitting down, and walking. So when my legs are super numb it can sometimes be hard to get around as I normally would.",
    "Before this numbness, for about two days I felt tingling in half my body, and I was worried that it was going to get worse. Then, the next morning, I woke up with significant paralysis in my legs and didn’t feel strong enough to do anything. I knew these were telltale signs of my MS symptoms, so I tried to calm myself down. My doctor prescribed me medication to reduce my MS relapse rates. I was hoping to decrease the time of the episode as well as prevent future flare-ups. After taking the medicine, I tried to relax by closing my eyes and letting things go. Keeping my mind and body relaxed can really help.",
    "After I took the pills and relaxed for a bit, I got ready for bed and then tried to sleep. Unfortunately, I can’t say that night was very peaceful. I kept feeling spasms in my legs, which made it hard to sleep. I also kept thinking about all the things that I needed to do, like getting groceries, finishing patient charts, and my work schedule I had the next day. I was lying in bed and instead of sleeping, I was thinking, ‘should I cancel things for tomorrow or just wait and see if I can tough it out?’ It was really frustrating.",
    "The next day I woke up early to ‘face a new day’ but my legs still had an ache/burning sensation and now I was also extremely tired. I knew I had to start the day, but my muscles were really tight. So I laid in bed and took a few minutes to just do some deep breathing and gentle stretching to try to soothe myself a little. After a while, I carefully got out of bed and tried to get started with my day. Try is the operative term. As I walked out of my bedroom toward the fridge to get some orange juice, I couldn’t feel my limbs and had trouble balancing. I froze and leaned over the counter to gain some stability. Words really can’t describe the fear and pain I felt. I couldn’t do anything about it, but wait for it to pass.",
    "I needed a break, so I made my way back to my bed to lie down. By the time I made it to the bed, I was extremely fatigued. My day was supposed to just be beginning but it felt like it had already ended. I had all these plans for what I needed to do that day. I was supposed to meet with a new patient. Plus, I needed to deliver some letters and pick up my prescriptions but then I couldn’t do any of those things I had planned. This is just one instance of the attacks that I have experienced since my diagnosis. I just wanted to share my experience with my chronic illness with you.",
    "Thank you for sharing. Please return to the qualtrics survey you were on before our chat and continue with the rest of the questions.",
  ],
  [
    "Hello! Thank you for participating in our study on healthcare communication!",
    "Please share the symptoms you experience with your primary physical chronic illness. Be as concise and straightforward as possible.",
    "PATIENT RESPONDS",
    "I also have a chronic condition. A few years back, I was diagnosed with Multiple sclerosis. I was really surprised because I have always lived a healthy lifestyle, and before that I had been going along normally. It’s a painful disease and so far there is really no way to cure it. It eventually will cause blurred vision, muscle weakness, and fatigue but right now it’s mostly numbness in my body. Sometimes it’s just my legs and arms that get tingling, but on other days, the numbness gets quite bad. My MS attacks tend to happen a few times a year. They mainly only happen about one to two times a year, so for the most part I’m still able to live my day to day life. But my episodes can be very grueling when they do happen.",
    "There was one time, about a year ago, where it became unbearable. It was mostly in my legs more than anything else, and I was experiencing extreme fatigue. The worst part about the numbness is that it really interferes with my day-to-day life because of course your limbs are so central to moving around: getting up, sitting down, and walking. So when my legs are super numb it can sometimes be hard to get around as I normally would.",
    "Before this numbness, for about two days I felt tingling in half my body, and I was worried that it was going to get worse. Then, the next morning, I woke up with significant paralysis in my legs and didn’t feel strong enough to do anything. I knew these were telltale signs of my MS symptoms, so I tried to calm myself down. My doctor prescribed me medication to reduce my MS relapse rates. I was hoping to decrease the time of the episode as well as prevent future flare-ups. After taking the medicine, I tried to relax by closing my eyes and letting things go. Keeping my mind and body relaxed can really help.",
    "After I took the pills and relaxed for a bit, I got ready for bed and then tried to sleep. Unfortunately, I can’t say that night was very peaceful. I kept feeling spasms in my legs, which made it hard to sleep. I also kept thinking about all the things that I needed to do, like getting groceries, finishing patient charts, and my work schedule I had the next day. I was lying in bed and instead of sleeping, I was thinking, ‘should I cancel things for tomorrow or just wait and see if I can tough it out?’ It was really frustrating.",
    "The next day I woke up early to ‘face a new day’ but my legs still had an ache/burning sensation and now I was also extremely tired. I knew I had to start the day, but my muscles were really tight. So I laid in bed and took a few minutes to just do some deep breathing and gentle stretching to try to soothe myself a little. After a while, I carefully got out of bed and tried to get started with my day. Try is the operative term. As I walked out of my bedroom toward the fridge to get some orange juice, I couldn’t feel my limbs and had trouble balancing. I froze and leaned over the counter to gain some stability. Words really can’t describe the fear and pain I felt. I couldn’t do anything about it, but wait for it to pass.",
    "I needed a break, so I made my way back to my bed to lie down. By the time I made it to the bed, I was extremely fatigued. My day was supposed to just be beginning but it felt like it had already ended. I had all these plans for what I needed to do that day. I was supposed to meet with a new patient. Plus, I needed to deliver some letters and pick up my prescriptions but then I couldn’t do any of those things I had planned. This is just one instance of the attacks that I have experienced since my diagnosis. I just wanted to share my experience with my chronic illness with you.",
    "Thank you for sharing. Please return to the qualtrics survey you were on before our chat and continue with the rest of the questions.",
  ],
  [
    "Hello! Thank you for participating in our study on healthcare communication!",
    "Those who have a physical chronic illness have stories that they share when it comes to their illness. Sometimes there is one particular memory that stands out for you related to your illness. This memory often has some of the following attributes:",
    `\u2022 It is a memory regarding your illness that has occurred before or after diagnosis.\n\u2022 It is a memory related to your illness for a specific moment or event that is very clear in your mind. It stands out in your mind. It probably still feels important to you even as you think about it, and it may lead to strong feelings\n\u2022 It is a memory you might tell someone else if that person asked about what it is like to have your physical chronic illness.\n\u2022 It is a memory that you think about when you think of your chronic illness. It feels vivid/clear, and may even feel familiar.`,
    "Please write about the memory you have that you always think about in regards to your illness. Please be as specific as possible, and be sure to include what happened, who was there, where it was, and when it happened. Do not share identifying information (like your name, address, etc.). Feel free to write as much as you want (the more the better) about your memory.",
    "PATIENT RESPONDS",
    "Thank you for sharing. Please return to the qualtrics survey and continue with the study measures.",
  ],
  [
    "Hello! Thank you for participating in our study on healthcare communication!",
    "Please share the symptoms you experience with your primary physical chronic illness. Be as concise and straightforward as possible.",
    "PATIENT RESPONDS",
    "Thank you for sharing. Please return to the qualtrics survey and continue with the study measures.",
  ],
];

export default { questions };
